name: Deploy
on:
  push:
    branches:
      - master
jobs:
  Merge-master-into-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master into release
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: release
          message: Merge master into release
          github_token: ${{ secrets.GITHUB_TOKEN }}
