name: Deploy
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          npm ci
          git reset --hard

      - name: Build App
        run: npm run build-only

      - name: Upload files to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          local-dir: ./dist/

  Merge-master-into-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master into release
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: release
          message: Merge master into release
          github_token: ${{ secrets.GITHUB_TOKEN }}
